name: CI for Remote HelloWorld

on: 
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8 Test
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
    
    - name: Checkout Own Repo to cloud
      uses: actions/checkout@v2
      with: 
        repository: lowkh/HelloWorldTestRun
    
    - name: Checkout private repo remotely
      uses: actions/checkout@v2
      with:
        repository: lowkh2/DevOpsQARepo
        path: tests
        token: ${{ secrets.QA_REMOTE }}
        
      
    - name: Begin Pytest
      run: |
        ls
        mv ./tests/*.* ./
        pytest --cov
